apiVersion: v1
kind: ConfigMap
metadata:
  name: documentetl-config
  labels:
    app: documentetl
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://pgvector-db:5432/ai_advisor_db?currentSchema=document_etl,public
  SPRING_DATASOURCE_USERNAME: advisor_user
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  SPRING_CLOUD_GCP_CREDENTIALS_LOCATION: file:/var/run/secrets/documentetl-gcp/gcp-vertex-key.json
  VERTEX_LOCATION: us-central1
  LANGCHAIN4J_VERTEX_LOCATION: us-central1
  LANGCHAIN4J_CHAT_LOCATION: us-central1
  APP_EVALUATION_BIGQUERY_ENABLED: "false"
  APP_MLFLOW_ACTION_LOGGING_ENABLED: "false"
