apiVersion: v1
kind: Secret
metadata:
  name: documentetl-secrets
  labels:
    app: documentetl
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: password
  VERTEX_PROJECT_ID: demoproject
  LANGCHAIN4J_VERTEX_PROJECT: demoproject
  LANGCHAIN4J_CHAT_PROJECT: demoproject
  gcp-vertex-key.json: |
    {
      "replace": "gcp-gcp-json"
    }
